apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tortuga-loot
  namespace: {{namespace}}
  labels:
    team: teampeon
spec:
  image: repo.adeo.no:5443/tortuga-loot
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: isAlive
  readiness:
    path: isReady
  replicas:
    min: 3
    max: 20
  resources:
    limits:
      cpu: 1000m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
  vault:
    enabled: true
  prometheus:
    enabled: true
